### PR TITLE
reformat using astyle

### LINKED ISSUE #179: Mixed whitespace
My OCD (just kidding) is asking me to fix FluidSynth's source-code whitespace, as I have noticed that it contains mixed-style tabs and spaces. We even have one line with "misleading indentation", which will be fixed when cleaning up.
What is your project-specific whitespace/indentation policy? Personally (and professionally) I prefer 2 spaces per level, no tabs.
Also, any interest to pass the code through clang-format or uncrustify, while we're at it?
Or are you worried about messing up the file history (e.g. for "blame")?
I already made a fork and would send you PRs when I got something. Is that OK for you?

### PR DESCRIPTION
**Pull request by derselbst**
Proposes to reformat the code solely using `astyle` (f373e87) and additionally forcing a column limit of 100 (5a5d794).

Resolves #179.
Closes #402.
Closes #403.

### CODE REVIEW

**Comment by mawe42** [comment]
That looks *much* better in my opinion! Not as complete as the clang-format, but not as intrusive either. Some inconsistencies like ```if (args)``` vs. ```if(args)``` are not cleaned up, but those are not really bad for readability.

So, thumbs-up for this version!

**Comment by derselbst** [comment]
> That looks much better in my opinion!

With or without 100 char limit?

**Comment by derselbst** [comment]
> inconsistencies like if (args) vs. if(args) are not cleaned up,

Can be fixed with the `-H` option.

**Comment by mawe42** [comment]
The forced 100 char column break does seem to mess up some things again, though. Maybe leave that step out and do line length formatting manually if code needs to be touched anyway?

**Comment by derselbst** [comment]
Ok, forced pushed, now without column limit and consistent `if(arg)`. First used astyle to format, then used clang-tidy to add missing braces that astyle didnt find, fixed the compilation bugs introduced by clang-tidy and ran astyle again... duh. So I kept the .clang-format config for now, as it may be used by clang-tidy to correctly apply missing braces.

**Comment by jjceresa** [comment]
I have not fully understood. Is this processing pipeline breaks line above a given length limit ?. Which is this limit ?.

**Comment by derselbst** [comment]
Right now there is no column limit, i.e. no forced line breaks here.

**Comment by mawe42** [comment]
This looks very good, in my opinion!

I would prefer a space after ```if (arg)```, ```while (arg)``` etc to separate them from "normal" function invokations, but that is again very personal.

**Pull request merged**
