### PR TITLE
Fix for LADSPA chorus send port.

### PR DESCRIPTION
**Pull request by jnonis**

### CODE REVIEW

**Comment by jnonis** [comment]
There you have it!!!

**Comment by mawe42** [comment]
Well spotted, thanks. Looks good.

**Comment by derselbst** [comment]
Three exclamation marks look quite annoyed. OpenSource development only works when the community submits fixes back to upstream, so that other users can profit from that. I cant look through all downstream modifications all day and pull in the fixes myself. So dont be selfish or lazy by keeping the fixes for yourself. You did a good job and should be willing to share it *voluntarily*. Thanks!

**Comment by jnonis** [comment]
@derselbst I think you misunderstood my comment, I'm not a english native speaker and sometimes I don't express myself properly. It didn't bother me that you ask for a pull request and I glad to contribute to with project.

**Comment by mawe42** [comment]
@jnonis btw: if you actually use the LADSPA subsystem and have any other suggestions, feature requests etc, I would be grateful if you would raise them on the fluid-dev mailinglist.

**Comment by derselbst** [comment]
Ok then, sry.

**Pull request merged**
