### PR TITLE
Add Android testing setup

### PR DESCRIPTION
**Pull request by atsushieno**
context: https://github.com/FluidSynth/fluidsynth/issues/912

This adds basic testing setup along with custom build scripts and test source generator scripts.

The rationale behind the app and how-to documentation to set up and run both locally and on Azure DevOps are described on `test-android/README.md`.

Changes are rebased off of master HEAD and can be either packed in merge-commit or merged as is (some extraneous reverts involved though).

### CODE REVIEW

**Comment by atsushieno** [comment]
Some defects I'm aware of:

- Azure DevOps setup is not done. Maybe it can be done based on existing information like [this](https://medium.com/genetec-tech/android-ui-testing-in-azure-devops-81bbe7cea9fd). I'm still unsure if setting up emulator costs too much build time and/or network resources and have no idea how the team can afford to accept the cost, so I would leave it to @derselbst for now, but feel free to delegate it to me if it was not easy, it would certainly require some Android development background.
- The package versions are hard-coded on build-scripts/build-env.sh as they were just copied from Azure DevOps setup. Ideally they had better be retrieved from somewhere, but that would affect how you manage the builds. Considering that it would not be too version dependent, at this state I leave them as is.

**Comment by derselbst** [comment]
Works like a charm! I only added a missing `mkdir` and relaxed the CMake version check. I'll keep the commit history when merging this, as it could be helpful in the future to understand the trouble you've been through :)

One question: Currently, a single `gradlew build` command handles all four arch. How does gradle know that it should handle those four archs? I couldn't find that place. I'm asking because in ADops we will only be able to handle a single arch.

**Comment by atsushieno** [comment]
awesome!

> One question: Currently, a single `gradlew build` command handles all four arch. How does gradle know that it should handle those four archs? I couldn't find that place. I'm asking because in ADops we will only be able to handle a single arch.

Looks like Azure DevOps has awkward limitation.. I just added an customizible build property. Now you can run gradle like: `./gradlew connectedCheck -PcustomAbiFilters=x86`

**Comment by derselbst** [comment]
Perfect, thank you! I'm merging this and in the next days / weeks will work in the ADops integration.

> Looks like Azure DevOps has awkward limitation

It's intentional: You get up to 10 parallel build slots in Azure, but each virtual machine only gets a dual-core CPU. Building all four archs on a single VM takes way too long (for my taste). But building each architecture in a different slot reduces overall build time by factor four ;)

**Pull request merged**
