### PR TITLE
fix intial player state

### PR DESCRIPTION
**Pull request by jjceresa**
This PR addresses issue https://github.com/FluidSynth/fluidsynth/issues/763.

### CODE REVIEW

**Review by derselbst — COMMENTED** [review]
This would mean that `FLUID_PLAYER_READY` becomes unused. But the status is still exported to clients via `fluid_player_get_status` and they might depend on this state in some way.

**Comment by jjceresa** [comment]
>This would mean that FLUID_PLAYER_READY becomes unused.

yes.

>But the status is still exported to clients via fluid_player_get_status and they might depend on this state in some way.

Yes, but as this FLUID_PLAYER_READY value has actually an incorrect meaning for client, perhaps this value should be deprecated ?. Also perhaps the value FLUID_PLAYER_DONE should be renamed FLUID_PLAYER_STOPPED which is more understandable ?.

**Comment by derselbst** [comment]
> Also perhaps the value FLUID_PLAYER_DONE should be renamed FLUID_PLAYER_STOPPED which is more understandable ?.

Maybe. But this change would unnecessarily break client code. I would rather vote to improve the documentation.

> Yes, but as this FLUID_PLAYER_READY value has actually an incorrect meaning for client, perhaps this value should be deprecated ?.

Same. Also I think it's important to retain an enum that describes the "initial state" of the player, see my other PR.

**Comment by jjceresa** [comment]
>Maybe. But this change would unnecessarily break client code. I would rather vote to improve the documentation.

Ok.

>Same. Also I think it's important to retain an enum that describes the "initial state" of the player. see my other PR.

Ok. Please which PR ?

**Comment by jjceresa** [comment]
>Ok. Please which PR ?

I think that we can close this PR and take your solution instead.

**Comment by jjceresa** [comment]
>I think that we can close this PR and take your solution instead.

I think that we can close https://github.com/FluidSynth/fluidsynth/pull/762 and take your solution instead.

**Comment by derselbst** [comment]
Superseded by #765

**Pull request closed without merging**
