### PR TITLE
Small math simplify

### PR DESCRIPTION
**Pull request by carlo-bramini**

### CODE REVIEW

**Comment by derselbst** [comment]
`fluid_hz2ct` looks a little over-engineered, given the fact that it isn’t used anywhere (?). Don’t know how to deal with that. The rest looks fine.

**Comment by mawe42** [comment]
`fluid_hz2ct` was in the initial code drop by Peter and seems to have never been used anywhere. Maybe simply remove it? If we decide to keep it, I would vote to leave it as is, not optimise it.

**Comment by carlo-bramini** [comment]
I'm sorry, I did not notice that fluid_hz2ct was unused. You can drop all the changes on that function if you want.

**Comment by derselbst** [comment]
> Maybe simply remove it?

I would like to keep it for educational purpose, possibly commenting it out. IIRC the spec is a little complicated when it comes to cents <--> hertz.

**Comment by mawe42** [comment]
Sound good.

**Pull request closed without merging**
