### PR TITLE
jack midi autoconnect

### PR DESCRIPTION
**Pull request by ColinKinloch**
"midi.autoconnect" option for the jack driver.

Related to #414.

### CODE REVIEW

**Comment by ColinKinloch** [comment]
I changed it to autoconnect during the jack process callback which may not be ideal as anything in there should be "suitable for real-time execution". It can't be run in the port registration callback. 
Is there a more appropriate time to have it run?

**Comment by derselbst** [comment]
> It can't be run in the port registration callback. Is there a more appropriate time to have it run?

The process callback is indeed unsuitable, as there is memory allocation going on in `jack_get_ports()`. Why isn't it possible in the registration callback itself?

**Comment by ColinKinloch** [comment]
Jack gives the error "Cannot callback the server in notification thread!" on jack_connect an the connection isn't established.

**Comment by derselbst** [comment]
Tested and works as expected. Thanks!

**Pull request merged**
