### PR TITLE
Keep pedaling (sustain or sostenuto) effective when the same note is played more than once.

### PR DESCRIPTION
**Pull request by jjceresa**
When playing the same note more than once the previous note is forced in release stage except if pedaling (sostenuto or sustain) is active. This makes it sound more like a real piano. See https://lists.nongnu.org/archive/html/fluid-dev/2021-06/msg00001.html

### CODE REVIEW

**Comment by jjceresa** [comment]
@mrbumpy409 This PR should fix the behaviour you started on the mailing list (https://lists.nongnu.org/archive/html/fluid-dev/2021-06/msg00001.html).
Please, could you have a try on your side to confirm that it works as expected ?.

**Review by derselbst — COMMENTED** [review]
Looks correct to me. But I would like to test this behaviour with overlapping notes in the next days. Can you remember why you wanted pedaling to be ignored back then?

**Comment by jjceresa** [comment]
>Can you remember why you wanted pedaling to be ignored back then?

If I remember well, I noticed that when playing the same note more than once while pedaling this result in sound growing louder. I was thinking that this wasn't natural. I was wrong because in fact this is very natural on real acoustic piano for which keeping the previous note still alive allows a fluid legato playing with following notes played at different dynamics (i.e velocity).

**Comment by jjceresa** [comment]
>But I would like to test this behaviour with overlapping notes in the next days.

For overlapping same note, new voices (with respective velocity) will be started for each following noteon. On noteoff these voices will be sustained by the active pedal. Then when the pedal become inactive, all voices are released at the same time.

**Review by derselbst — APPROVED** [review]
Works well, thanks!

**Pull request merged**
