### PR TITLE
Fix static mingw linking issues

### PR DESCRIPTION
**Pull request by realnc**
This is needed to be able to a static mingw build. This patch has been carried by MXE for quite a while now but hasn't been submitted upstream:

https://github.com/mxe/mxe/blob/master/src/fluidsynth-1-fixes.patch

I rebased that patch to the current version of fluidsynth (MXE is still shipping an older version.)

### CODE REVIEW

**Comment by realnc** [comment]
```
[100%] Linking CXX executable fluidsynth.exe
/mnt/Data/mxe/usr/bin/i686-w64-mingw32.static-ld: libfluidsynth.a(fluid_samplecache.c.obj):fluid_samplecache.c:(.text+0x217): undefined reference to `mlock'
/mnt/Data/mxe/usr/bin/i686-w64-mingw32.static-ld: libfluidsynth.a(fluid_samplecache.c.obj):fluid_samplecache.c:(.text+0x231): undefined reference to `mlock'
/mnt/Data/mxe/usr/bin/i686-w64-mingw32.static-ld: libfluidsynth.a(fluid_samplecache.c.obj):fluid_samplecache.c:(.text+0x252): undefined reference to `munlock'
/mnt/Data/mxe/usr/bin/i686-w64-mingw32.static-ld: libfluidsynth.a(fluid_samplecache.c.obj):fluid_samplecache.c:(.text+0x3b1): undefined reference to `munlock'
/mnt/Data/mxe/usr/bin/i686-w64-mingw32.static-ld: libfluidsynth.a(fluid_samplecache.c.obj):fluid_samplecache.c:(.text+0x3c7): undefined reference to `munlock'
collect2: error: ld returned 1 exit status
```

**Comment by realnc** [comment]
> However, it surprises me that your MinGW finds `sys/mman.h`. Can you please provide your build commands and the version of mingw you're using? So that I can add a CI test and then we'll see how to incorporate your patch.

It's just a bog-standard cmake invokation:

```none
mkdir build
cd build
i686-w64-mingw32.static-cmake ..
make -j`nproc`
```

`sys/mman.h` is provided by:

https://code.google.com/archive/p/mman-win32/

In MXE, this is provided by the mman-win32 package:

https://github.com/mxe/mxe/blob/master/src/mman-win32.mk

If you need a test environment to build this, you can use the `realnc/qtads-build:mxe-x86` docker image (it's on Docker Hub so you can just pull it with that name.)

**Comment by derselbst** [comment]
Ok, thanks for the docker hint. I'll look into this!

**Comment by realnc** [comment]
I pushed a reworked version of this that uses the existing `WINDOWS_LIBS` CMAKE variable. I also moved `Requires` to `Requires.private`.

**Pull request merged**
