### PR TITLE
cmake: enable ladspa by default

### PR DESCRIPTION
**Pull request by derselbst**
@mawe42 any reason not to do it?

### CODE REVIEW

**Comment by mawe42** [comment]
Well, it's not quite finished yet. I'm still working on getting it right. A few concepts don't work well in certain setups. I have nearly finished adding the last remaining bits and cleaning it up again, but I don't want to make the same mistake again: submitting a feature that isn't complete yet. I shouldn't have requested a pull yet, just a branch review.

So please wait with this until it's all done. Enabling it by default will probably make sense then, though.

**Comment by derselbst** [comment]
Ok

**Comment by mawe42** [comment]
Ok, the LADSPA refactor is nearly done, I think. Latest code in the ladspa branch. When people have given feedback and we're all happy, I'll incorporate this into the ladspa branch, ok?

**Comment by derselbst** [comment]
Sure. You could have also cherry-picked it right now so that any potential user testing the branch doesnt get used to manually `-Denable-ladspa=1`.

Anyway, nice work!

**Comment by mawe42** [comment]
This commit is now part of the ladspa branch.

**Pull request closed without merging**
