### PR TITLE
Compile time constant lookup tables (updated)

### PR DESCRIPTION
**Pull request by derselbst**
Calculate lookup tables during compile time, as intended by #417.

* cleaned up commit history
* use a more accurate constexpr sin()
* fix calculation of sinc table
* add a unit test to verify accuracy to legacy runtime initialized lookup tables

#### TODO:
- [ ] memory consumption for all compilers very high (>3GiB)
- [x] ~~MSVC entirely fails (out of heap space)~~ (wont fix)
- [x] clang-tidy may be killed fails

### CODE REVIEW

**Comment by derselbst** [comment]
Sry, I dont know to which change you are referring. However, all the interpolation tables of fluid_rvoice_dsp.c are correctly placed in the .rodata section, provided that you set the cmake flag.

**Comment by carlo-bramini** [comment]
Ouch, you are right, I have seen where the const keyword is. ^^;

Perhaps, since it could be used by more than one file, it could be emitted by cmake into config.h something like this:
`#define CONST_CTABLE const`
or:
`#define CONST_CTABLE /* empty */`
depending on the flag at configure time, to simplify a bit more.

**Comment by derselbst** [comment]
Ok, will do so.

**Comment by carlo-bramini** [comment]
I had also seen the crash with MSVC... but perhaps it can be fixed without much work if we want: instead of using a cumulative base 10 inside auto_gen_array.h, the same thing but made with base 2 can be used instead. I will try to do some experiments.

**Comment by derselbst** [comment]
Any success with MSVC?

**Comment by carlo-bramini** [comment]
I did some experiments and I did a solution that in my opinion should use less memory, but MSVC6 still does not work. I have not tried newer versions of the compiler at the moment.

**Pull request closed without merging**
