### PR TITLE
Fix incorrect usage of fluid_ct2hz()

### LINKED ISSUE #456: Incorrect usage of fluid_ct2hz()
### FluidSynth version 
<= 2.0.x

### Current behavior
[It seems that `fluid_ct2hz()` is mistakenly used in GEN_OVERRIDEROOTKEY.](https://github.com/FluidSynth/fluidsynth/blob/da6a2e7a91820bf97f89d3bcdb15b76e94e90bc2/src/synth/fluid_voice.c#L839)

### Expected behavior
Because `fluid_ct2hz()` secretly clips to 13500 cents (upper fc limit), `fluid_ct2hz_real()` should be used instead. (ok, `fluid_ct2hz_real()` clips it to 14100 cents...)

### PR DESCRIPTION
**Pull request by derselbst**
Fixes #456 .

### CODE REVIEW

**Comment by jjceresa** [comment]
`fluid_ct2hz(cent)` behaves monotonically in the range [1500..13500] cents.
`fluid_ct2hz_real(cent)` isn't monotonic (because for cent > 14100, the frequency jump back to 1Hz). 

`fluid_ct2hz()` is still used here in `fluid_iir_filter_calc()` (fluid_iir_filter.c- line 377).
-1) It seems that `here` is the correct usage of fluid_ct2hz(cent) because we need a monotonic behaviour ?.

- 2)I wonder why `fluid_ct2hz_real()` isinsight the right usage for `root_pitch_hz` initialization ?.

-3)I wonder why `fluid_ct2hz_real()` is the right usage during `phase calculation` (fluid_rvoice.c-line 375), instead of `fluid_ct2hz()` ?.

Any feedback will be appreciated.

**Comment by jjceresa** [comment]
`fluid_ct2hz(cent)` behaves monotonically in the range [1500..13500] cents.
`fluid_ct2hz_real(cent)` isn't monotonic (because for cent > 14100, the frequency jump back to 1Hz).

`fluid_ct2hz()` is still used here in `fluid_iir_filter_calc()` (fluid_iir_filter.c- line 377).
-1) It seems that here is the correct usage of `fluid_ct2hz()` because we need a monotonic behaviour ?.

-2) I wonder why `fluid_ct2hz_real()` is the right usage for `root_pitch_hz` initialization ?.

-3) I wonder why `fluid_ct2hz_real()` is the right usage during `phase calculation` (fluid_rvoice.c-line 375), instead of `fluid_ct2hz()` ?.

Any feedback will be appreciated.

**Comment by derselbst** [comment]
For me what matters is that `fluid_ct2hz_real` is our general cents to hertz conversion function, that we basically should use everywhere. `fluid_ct2hz` limits the convertible range to satisfy `initialFilterFc` generator requirements, so it's only appropriate for IIR filter stuff. Why fluid_ct2hz_real jumps to 1Hz I can't tell. Doesn't really make sense to me, I'm open to change this behaviour.

**Comment by jjceresa** [comment]
>For me what matters is that fluid_ct2hz_real is our general cents to hertz conversion function, that we basically should use everywhere. fluid_ct2hz limits the convertible range to satisfy initialFilterFc generator requirements, so it's only appropriate for IIR filter stuff.

Ok, we must think of `fluid_ct2hz()` being a sub range of `fluid_ct2hz_real()`.

>Why fluid_ct2hz_real jumps to 1Hz I can't tell. Doesn't really make sense to me, I'm open to change this behaviour.

This doesn't make sense for me also:
We could replace fluid_conv.c- line 85
 `return (fluid_real_t) 1.0; /* some loony trying to make you deaf */`
by 
 `return (fluid_real_t) 28160.0; /* some loony trying to make you deaf */`

**Comment by derselbst** [comment]
...or fall-back to "on-the-fly computation" rather than some hardcoded value.

**Comment by jjceresa** [comment]
...`fluid_ct2hz_real()` being used at synthesis time during `phase calculation` (fluid_rvoice.c-line 375),  we should pay attention that "computing-on-the-fly" is cpu-fpu expensive.

**Comment by derselbst** [comment]
I was referring to the very rare case when cent > 14100 .

**Comment by jjceresa** [comment]
In current implementation each `hardcoded frequency value` is obtained by multiply the previous one by 2:......7040.0, 14080.0, 28160.0 (the last one).
For the very rare case (last one) we could also do "on-the-fly computation" . Regardless the implementation the result should be upper limited to avoid `make us deaf` :).

**Comment by derselbst** [comment]
Merging this one, follow up in #569.

**Pull request merged**
