### PR TITLE
Fix framework installation on MacOS

### LINKED ISSUE #1024: make install does not completely install components on MacOS
### FluidSynth version
FluidSynth runtime version 2.2.4
Copyright (C) 2000-2021 Peter Hanappe and others.
Distributed under the LGPL license.
SoundFont(R) is a registered trademark of Creative Technology Ltd.

FluidSynth executable version 2.2.4
Sample type=double

### Describe the bug
Installation from sources on MacOS is incomplete. The framework is installed with no headers, so it is impossible to use the API.

### Expected behavior
`make install `  installs all required components. Ideally, headers should be placed inside the framework, but at least they should be installed in a public location (e.g. ${CMAKE_INSTALL_PREFIX}/include). 

### Steps to reproduce
- `make install`
- try to compile a program using the Fluidsynth API.

### Additional context
Flluidsynth is used as a dependency for the Csound plugin fluidOpcodes. Installation worked correctly for 1.x, but not so for 2.2.4. I had to copy the headers by hand, which is not ideal. Note that pointing to use `brew` is not a solution for cases where we want to provide binary packages for users.

### PR DESCRIPTION
**Pull request by derselbst**
This includes Pedro's fix from #1027 along with adjustments to the CI pipeline and rebased against the `2.2.x` branch.

Resolves #1024

### CODE REVIEW

**Comment by derselbst** [comment]
@vlazzarini CI builds are passing now. Feel free to test.

**Comment by vlazzarini** [comment]
Thx. Here's what I did:

```
git clone https://github.com/FluidSynth/fluidsynth.git
cd fluidsynth
mkdir build 
cd build 
make -j 6 
sudo make install 
```

However, it doesn't look like the headers are there.  

```
victor@MU-LAP-7ZM build % ls /Library/Frameworks/FluidSynth.framework           
FluidSynth	Resources	Versions
```
I also looked at /Versions/3 to see if it was just them symlink that wasn't created.

am I in the wrong branch?

**Comment by derselbst** [comment]
You need the `mac-make-install` as written in the PR.

**Comment by vlazzarini** [comment]
oh, sorry. OK, now I get it built correctly, but installation in `/usr/local/Library/Frameworks` is non-standard. So I try then 

```
cmake .. -DCMAKE_INSTALL_PREFIX=/  
```

but that fails with

```
sudo make install
```
...

```
Install the project...
-- Install configuration: "RelWithDebInfo"
CMake Error at cmake_install.cmake:41 (file):
  file cannot create directory: /lib64/pkgconfig.  Maybe need administrative
  privileges.
```

The default install configuration does not seem to be what you would expect on MacOS (sounds like it's for a Debian installation).

**Comment by derselbst** [comment]
Have you cleaned your build folder before trying? Also, you're not supposed to manually set `CMAKE_INSTALL_PREFIX`, as this implementation relies on the fact that it's default initialized.

**Comment by vlazzarini** [comment]
yes, sorry, cleaned my build and now it installs  correctly, thanks.

**Review by derselbst — COMMENTED** [review]
Great, thanks for testing!

**Pull request merged**
