### PR TITLE
No longer prefix the lib folder for MSVC builds

### PR DESCRIPTION
**Pull request by stekyne**
As discussed in #333, I've remove the lib prefix for MSVC builds. 

Should resolve the issue with the VCPKG.

### CODE REVIEW

**Comment by derselbst** [comment]
"It should resolve the issue" sounds like a vague guess. Have you tested it with 1.1.9 whether it works?

**Comment by stekyne** [comment]
Tested both x64 and x64 static builds now. Works well. I've tested with a sample cmake project and header/libs are being found.

**Comment by stekyne** [comment]
I've used this FindFluidSynth.cmake.

# - Find fluidsynth
# Find the native fluidsynth includes and library
#
#  FLUIDSYNTH_INCLUDE_DIR - where to find fluidsynth.h
#  FLUIDSYNTH_LIBRARIES   - List of libraries when using fluidsynth.
#  FLUIDSYNTH_FOUND       - True if fluidsynth found.

if (FLUIDSYNTH_INCLUDE_DIR AND FLUIDSYNTH_LIBRARIES)
  # Already in cache, be silent
  set (FluidSynth_FIND_QUIETLY TRUE)
endif ()

find_path (FLUIDSYNTH_INCLUDE_DIR fluidsynth.h)

find_library (FLUIDSYNTH_LIBRARIES NAMES fluidsynth libfluidsynth)
mark_as_advanced (FLUIDSYNTH_LIBRARIES FLUIDSYNTH_INCLUDE_DIR)

# handle the QUIETLY and REQUIRED arguments and set FLUIDSYNTH_FOUND to TRUE if 
# all listed variables are TRUE
include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(FluidSynth DEFAULT_MSG FLUIDSYNTH_LIBRARIES FLUIDSYNTH_INCLUDE_DIR)

**Comment by derselbst** [comment]
Ok, nice. I'd like to look into the vcpkg config file for fluidsynth. Could you upload it as well?

**Comment by stekyne** [comment]
https://gist.github.com/stekyne/91ec20d9aeaa01b175b83fe4013fbda6

**Comment by stekyne** [comment]
Obviously the 1.1.9 zip won't work without these PR changes so I guess we'd have to switch it to whatever the next version is. Or else download the latest git version in the portfile instead.

**Comment by derselbst** [comment]
1.1.10 will be next (end of February I guess). Please **DO NOT** use buggy, unstable, recent git versions, there is not API/ABI stability guarantee if you do so.

Else this looks good. Will merge it tomorrow and add a few notes to the [wiki](https://github.com/FluidSynth/fluidsynth/wiki/BuildingWithCMake#building-with-visual-studio-on-windows). Thanks!

**Comment by stekyne** [comment]
Just on this. I finally integrated into csound as a static x64 build (in VCPKG). There are a few things though. You have to define FLUIDSYNTH_NOT_A_DLL for the static builds which I wasn't aware of. You'll also have to separately link in glib-2.0 and whatever else is missing. 

Perhaps we should set the "not a dll" flag in the port file seeing as we'll know the target triple.

**Comment by derselbst** [comment]
>  You have to define FLUIDSYNTH_NOT_A_DLL for the static builds

The only reason I see so far is that you probably dont want to have a
DllMain() function in your static lib? Does compilation or linkage
break if you do otherwise?

Besides: having thought a little more about this "static lib" idea, I
think it's a bad one. Two main reasons come to my mind:

1. Static libs dont provide symbol visibility, which we are enforcing
since 1.1.7, to avoid the emerging or support of broken downstream
apps using private functions of fluidsynth.
2. Fluidsynths license is LGPL. Any software statically linking in
fluidsynth must be (L)GPL as well. This is probably not the case for
windows apps, which are mostly proprietary.

People are lazy and due to the fact that vcpkg is a very comfortable
solution, static libs would probably encourage downstream to violate
fluidsynth's license when using it in their proprietary app, I could
imagine. Is there no way of providing a dll via vcpkg?

**Comment by stekyne** [comment]
There were build errors without that flag set. It was complaining about missing fluidsynth functions. 
https://github.com/FluidSynth/fluidsynth/blob/master/include/fluidsynth.h#L36
The FLUIDSYNTH_API was being set to __declspec(dllimport) without it. 

Yeah, you can build shared DLLS in VCPKG. That's mostly the default way of doing it but they provide support for static builds also. There is also the possibility of building in the CRT statically or dynamically if you wanted. https://github.com/Microsoft/vcpkg/blob/master/docs/users/triplets.md 

That's what I meant about target triplet earlier. You have to set how you want to install each package e.g. "vcpkg install fluidsynth:x64-windows-static fluidsynth:x64-windows". Which is the static 64bit and shared 64bit respectively. So in the portfile we could add any CMake flags to build it correctly for each type.

I was building it statically because that's the way we've been integrating 3rd party libs in Csound recently. Just by changing the target triplet in our appveyor file, we can link them in shared or statically which can be handy.

The license for Fluidsynth is copied with the VCPKG by their design so it should be very clear how it is to be used. I don't think there is any difference with someone who would download the source and build with CMake the same way.

**Comment by derselbst** [comment]
Ah, so since vcpkg supports shared and static version (and apparently
defaults to shared) I'm fine with this. However the build failure of static
windows builds is a bug in fluidsynths build system. I could think of some
fix that checks for if BUILD_SHARED_LIBS==0 then define not a dll flag.
Additionally I'll try to setup an appveyor CI build that tests static
builds for windows. I wont have time for this in the next days, but I'll do
so before 1.1.10. In the meantime, please open a new issue a.la. "Static
build fails on windows".

**Pull request merged**
