### PR TITLE
Include header files in Android Artifacts

### LINKED ISSUE #894: Header files are missing from Android release zip
Currently Android build artifacts on the Releases page are created from the new Azure pipelines. I noticed that it is missing headers and when we build apps that references fluidsynth API in our code we will have to get those headers from somewhere separately.

Windows release binary zip seems to contain the headers. I think it is the right way for Android too.

### Is your feature request related to a problem?

- when we build apps that references fluidsynth API in our code we will have to get those headers from somewhere separately, otherwise.

### Describe the solution you'd like

- Add `fluidsynth.h` in the archive too, probably within `include/fluidsynth` directory (assuming it is platform independent).

### Describe alternatives you've considered

- I could download headers manually.

### Additional context

Not sure if it is worth mentioning, but I make use of fluidsynth for Android in this app (which I think has build setup in closer mindset to the latest Android builds here rather than my original Cerbero builds), https://github.com/atsushieno/aap-lv2-fluidsynth (It is still not an intuitive use case and not for testing header inclusion at all.)

Checked release v2.2.1. It might be different from the latest azure pipeline settings.

### PR DESCRIPTION
**Pull request by derselbst**
Include header files and remove symbolic links to `so.x.y`. I had to change the folder structure a bit, it should be self-explaining though.

Resolves #894.

### CODE REVIEW

**Comment by derselbst** [comment]
Example artifact can be found here: https://dev.azure.com/tommbrt/tommbrt/_build/results?buildId=5280&view=artifacts&pathAsName=false&type=publishedArtifacts

**Comment by derselbst** [comment]
@atsushieno FYI

**Comment by atsushieno** [comment]
Yay it looks fixed!

Sorry one last thing, is there any reason you prefer "i686", "aarch64", and "arm" as subfolders? If they were "x86", "arm64-v8a", and "armeabi-v7a", then we can simply copy the archive contents into `src/main/jniLibs` directly, without separate steps for copying contents for each arch.

**Comment by derselbst** [comment]
> If they were "x86", "arm64-v8a", and "armeabi-v7a", then we can simply copy the archive contents into

Good hint! I'm now using `$ANDROID_ABI_CMAKE`.

**Pull request merged**
