### PR TITLE
Fix typos discovered by codespell

### PR DESCRIPTION
**Pull request by cclauss**
Fix typos discovered by codespell -- https://github.com/codespell-project/codespell
```
codespell --ignore-words-list=bloc,blocs,caf,capela,datas,egal,readd,rin,seh --skip="*.pdf" \
          --quiet-level=3 --write-changes
```

### CODE REVIEW

**Comment by pedrolcl** [comment]
> codepsell

I see what you did there 😄

**Review by derselbst — APPROVED** [review]
Thanks!

Codespell is great. I still keep dreaming of a containerized Github action that executes it monthly and opens a PR... never found time for that though.

**Comment by cclauss** [comment]
> a containerized Github action that executes it monthly

https://github.com/codespell-project/actions-codespell

Do you use https://pre-commit.com and https://pre-commit.ci?

**Comment by derselbst** [comment]
Oh, easier than thought, thanks for the pointer! And no, currently, we don't use any pre commit hooks or similar.

**Pull request merged**
