### PR TITLE
More LADSPA cleanup and refactor

### PR DESCRIPTION
**Pull request by mawe42**
- Contains the render cleanup from the previous (but closed) pull request
- Adds check for in-place broken plugins
- Restructures fluid_ladspa_check function into smaller units

### CODE REVIEW

**Comment by derselbst** [comment]
So because of a1ff8d0e55a588e893ca22bc6cd74afa41000f77 from now on the effect of any ladspa output node will be heard when pulling audio from the synth via `fluid_synth_(n)write_float()`? I'm fine with that. Just asking because I cant comprehend why it hasnt been done like that before.

**Comment by mawe42** [comment]
Sorry, I dont' understand your question... All that a1ff8d0 functionally changes is to reduce the number of times fluid_ladspa_run (and the run method of all plugins) is called when rendering more than one block at a time.

**Comment by derselbst** [comment]
Oh no, you're right. We are having buffers of buffers ofc. Argh.

**Comment by mawe42** [comment]
The old code with the VLAs duplicated *the pointers* into the mixer buffers. Just to be able to advance the pointers by adding FLUID_BLOCK to each one after the fluid_ladspa_run call.

**Comment by mawe42** [comment]
Great, thanks for the review!

**Pull request merged**
